FROM node:18

WORKDIR /app

# Copier les fichiers package.json et package-lock.json dans le container
COPY package*.json ./

# Installer les dépendances
RUN npm install


# Copier le reste des fichiers de ton projet dans le container
COPY . .

# Exécuter le serveur
CMD ["node", "server.js"]
