services:
  catalogue:
    build: ./catalogue
    ports:
      - "8081:8081"
    restart: unless-stopped

  commande:
    build: ./orders
    ports:
      - "8082:8082"
    depends_on:
      - catalogue
    restart: unless-stopped
